### ISSUE TITLE
Add support for strings from flash

### ISSUE THREAD

**Issue by sh-user** [mobizt/FirebaseJson#13]
Hi is it possible to add strings from flash for get and set function 
For example `json.get(result, PSTR("temp"));` or `json.get(result, FPSTR(F_temp));`

**Comment by sh-user** [comment]
Works `json.get(res, String(PSTR("temp")).c_str());` but probably there is another solution.

**Comment by mobizt** [comment]
It's already supported.

Which device you used which you think it's not supported.

**Comment by sh-user** [comment]
I have an ESP8266, if I write a PSR it causes a reboot.

**Comment by sh-user** [comment]
nonos sdk 2.2.1 (legacy) 
Arduino IDE 1.8.13

**Comment by mobizt** [comment]
For ESP8266 core version2.7.x and earlier I will add support flash string later.

**Comment by mobizt** [comment]
It is currently supported FPSTR which F and PSTR are not supported.

**Comment by sh-user** [comment]
Works like this
```
//global variables
const char F_temp[] PROGMEM = "temp";
uint8_t tmp = 0;
...
json.get(result, String(FPSTR(F_temp)).c_str());
tmp = result.to<int>();
```

**Comment by mobizt** [comment]
More simple with 
**json.get(result, pgm2Str(F_temp));**

pgm2Str is the macro defined in the library.

**Comment by mobizt** [comment]
The PGM_P (PROGMEM) **will not supported** as function arguments by the library due to it is ambiguous with the function that accepted const char*.

For F and PSTR macros will be supported later.
