### ISSUE TITLE
Error in compiling Create.ino example for Arduino IOT 33

### ISSUE THREAD

**Issue by JEG8** [mobizt/FirebaseJson#15]
Hi,

I ran into the following error when compiling the example code (create.ino) on an Arduino IOT 33.

In file included from \FirebaseJson\examples\BasicUsage\Create\Create.ino:13:0:
\libraries\FirebaseJson\src/FirebaseJson.h: In instantiation of 'typename mb_string::enable_if<mb_string::is_string<T>::value, bool>::type FirebaseJsonArray::dataRemoveHandler(T) [with T = const char*; typename mb_string::enable_if<mb_string::is_string<T>::value, bool>::type = bool]':

\libraries\FirebaseJson\src/FirebaseJson.h:1985:75:   required from 'bool FirebaseJsonArray::remove(T1) [with T1 = const char*]'

\examples\BasicUsage\Create\Create.ino:71:34:   required from here

\libraries\FirebaseJson\src/FirebaseJson.h:2037:17: error: cannot convert 'FirebaseJsonArray' to 'mb_string::enable_if<true, bool>::type {aka bool}' in return
         return *this;

**Comment by mobizt** [comment]
Thanks for reporting this issue.

The library update [v2.6.14](https://github.com/mobizt/FirebaseJson/releases/tag/v2.6.14) is available, please update.
