### ISSUE TITLE
Array of arrays

### ISSUE THREAD

**Issue by loczi1** [mobizt/FirebaseJson#16]
Hi!
Thanks for this useful library first of all!
I can use the FirebaseJsonArray to get an array from a specific level, but I found out the elements can be only values.
Is it possible to have arrays as the elements of each array items?
I want to iterate through the mapValues an elegant way..

`{
  "fields": {
    "temp": {
      "arrayValue": {
        "values": [
          {
            "mapValue": {
              "fields": {
                "x": {
                  "integerValue": "1"
                },
                "y": {
                  "integerValue": "21"
                }
              }
            }
          },
          {
            "mapValue": {
              "fields": {
                "x": {
                  "doubleValue": 79.536565324568613
                },
                "y": {
                  "doubleValue": 21.03846153846154
                }
              }
            }
          },
          {
            "mapValue": {
              "fields": {
                "y": {
                  "doubleValue": 20.884615384615387
                },
                "x": {
                  "integerValue": "144"
                }
              }
            }
          }
        ]
      }
    },
   }
},
  "createTime": "2022-02-17T18:30:44.121299Z",`

**Comment by mobizt** [comment]
If you know the exact relative path  of element  in array or object, you can get through any complex nested element.
No matter the element is array, object or primitive types.

The JSON you post is the object in array.

As you know, FirebaseJsonData that keep the parsing result stored array and object as string, to get array or object from it, you need to cast it to array or object like this.

https://github.com/mobizt/FirebaseJson/blob/9762610f5a45e51ca1050f7770d8dc23aab5c157/examples/BasicUsage/Create/Create.ino#L142-L143

In case to iterate through the nested array, you need to parse top level array to get the member element which stored in FirebaseJsonData.

If  member element (FirebaseJsonData) type is array then cast the FirebaseJsonData to array and iterate this second level array to get value.
