### ISSUE TITLE
Filtering deserialize

### ISSUE THREAD

**Issue by mocheffendi** [mobizt/FirebaseJson#20]
Hi Mobizt,

Iam new with json, how to filter deserialize this json data

```
[
	{
		"status": false,
		"room": "Emerald",
		"bed": "bed1"
	},
	{
		"status": true,
		"room": "Emerald",
		"bed": "bed2"
	},
	{
		"status": false,
		"room": "Emerald",
		"bed": "bed3"
	}
]
```
with 
if (status) {
 print room only if status true
 print bed only if status true
}

Thanks for your help

**Comment by mobizt** [comment]
It is not supported.
