### ISSUE TITLE
undefined reference to `bool FirebaseJson::set<unsigned char>(String const&, unsigned char)'

### ISSUE THREAD

**Issue by kenken64** [mobizt/FirebaseJson#3]
undefined reference to `bool FirebaseJson::set<unsigned char>(String const&, unsigned char)'

**Comment by mobizt** [comment]
Try the example first.

Please don't use this as a web board or forum that you can ask anything.

Please check the examples first.

**Comment by mobizt** [comment]
If you want me to help.

It is better to post your code and describe your problem instead of short answer like this.
